export class Orderdetails{
    ordername:string;
    orderprice:number;
    orderquantity:string;
    orderbrandname:string;
    orderbrandid:string;
    ordertotalprice:string
    constructor(
        ordername:string,
        orderprice:number,
        orderquantity:string,
        orderbrandname:string,
        orderbrandid:string,
        ordertotalprice:string){
            this.ordername=ordername
            this.orderprice=orderprice
            this.orderquantity=orderquantity
            this.orderbrandname=orderbrandname
            this.orderbrandid=orderbrandid
            this.ordertotalprice=ordertotalprice
    }
}  
export class OrderModel{
    customername:string;
    customercontact:string;
    customeraddress:string;
    customerid:string;
    totalprice:string;
    totalorder:string;
    time:string;
    orderstatus:string;
    order:Orderdetails[];
constructor(customername:string,
            customercontact:string,
            customeraddress:string,
            customerid:string,
            totalprice:string,
            totalorder:string,
            time:string,
            orderstatus:string,           
            ){
                this.customername=customername
                this.customercontact=customercontact
                this.customeraddress=customeraddress
                this.customerid=customerid
                this.totalprice=totalprice
                this.totalorder=totalorder
                this.time=time
                this.orderstatus=orderstatus
                this.order=[]              
            }
}